### ISSUE TITLE
A minor problem

### ISSUE THREAD

**Issue by SoYoung1111** [SNU-HPCS/CryoModel#1]
I'm interested in your papers and I would like to study the CryoModel. Bu I failed to run the command "python3.8 run.py ./configs/DRAM.cfg 77 22 1.2 0.4 262144 dram 1.2 0.4" and I was told that ModuleNotFoundError: No module named 'cacti.cacti_interface_pb2'. Besides, I failed to compile cacti. Could you please tell me how to solve this problem?

**Comment by ehdans06** [comment]
Hi Soyoung.
Thanks for your interest!

run.py use cacti executable; so you should compile cacti before running run.py.
Can you share me the exact problem (e.g., error log) when you compiled cacti?
(In fact, gcc/g++ version can be the problem because cacti hardcodes the gcc/g++ version in “cacti.mk” file. If it is the main problem, you can resolve it by changing the gcc/g++ paths in the .mk file)

**Comment by SoYoung1111** [comment]
Hi, Mr. Min.
I‘m glad that I've received your reply.
I have compiled cacit successfully. But I face a new problem now.
When I executed the command "python3 run.py ./configs/DRAM.cfg 77 22 1.2 0.4 262144 dram 1.2 0.4", I received the following feedback:

Traceback (most recent call last):
  File "run.py", line 148, in <module>
    main()
  File "run.py", line 140, in main
    hp_results = pgen.run(args.pgen, pgen.mosfet_mode.HP, args.temperature, args.node, args.vdd, args.vth)
  File "/home/suyang/CryoMem/CryoModel-main/CryoMEM/pgen.py", line 73, in run
    parse_output(pgen_output.output_parameter, check_output(cmd, text=True, cwd=os.path.dirname(pgen)))
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'text'

I'm not sure if the problem results from my version of Python or what else. (My version of Python is 3.6.9)
Looking forward to your reply again. Thanks!

**Comment by ehdans06** [comment]
Hi, Soyoung.

It seems like the Python version-related problem because the 'text' parameter has been added since 3.7 (https://stackoverflow.com/questions/52663518/python-subprocess-popen-doesnt-take-text-argument).
We suggest running run.py with python3.8; "python3.8 run.py ./configs/DRAM.cfg 77 22 1.2 0.4 262144 dram 1.2 0.4".

Thanks,
Dongmoon Min

**Comment by SoYoung1111** [comment]
OK，I will try it. Thank you very much！
