### ISSUE TITLE
Can this tool support the environment with the temperature of 4.2K?

### ISSUE THREAD

**Issue by Flians** [SNU-HPCS/CryoModel#2]
Hi,
Can this tool support the environment with the temperature of 4.2K?
If that, how can I do it?
Thank you.

**Comment by ehdans06** [comment]
Hi,
Thanks for your interest!
Unfortunately, we are not yet supporting 4K, but we plan to support it in the future update.

Thanks!
Dongmoon Min.

**Comment by ehdans06** [comment]
Hi,

Basically, the problem is due to the precision limit of Python.
There are several ways to solve it.

One suggestion is to hold the ni result constant below some temperature like this (with some error, but will be very little).
![image](https://user-images.githubusercontent.com/21350262/186074514-bc16b92c-5b2e-4d89-ad85-68f64ba91cc3.png)

Other suggestions are (1) you should find another equation in other references, or (2) use the variable with higher precision than double in Python.

**Comment by ehdans06** [comment]
It is also the precision-related problem (of CACTI).
Specifically, when the input PMOS leakage is zero, CACTI returns that error.
In that case, we recommend you to (1) use the variable with higher precision in CryoMEM/run.py, or (2) insert a very small value to CACTI when "Isub,pmos=0".
(like below)
![image](https://user-images.githubusercontent.com/21350262/186098407-1a72fe22-7926-438f-9a6a-493a6f39a6d1.png)

**Comment by ehdans06** [comment]
Can you share the input CACTI config and Vdd, Vth, technology node setups?
CACTI also reports the error when (1) Ion is too low or (2) the input memory config is invalid.

**Comment by ehdans06** [comment]
Sorry for the late response.
I recently disclose the 4K version of CryoModel.
Please pull the latest version and check it.

I also note that the 4K version of CryoModel is not validated, so be aware of the status for your research.

Thanks,
